name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送 v 开头的标签时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Setup JRE
      run: |
        ./create-jre.bat
        
    - name: Create README
      run: |
        ./create_readme.bat
        
    - name: Package Application
      run: |
        ./package.bat
        
    - name: List Files
      run: |
        dir
        echo "Current directory content:"
        dir /s /b
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/todo-reminder.zip
        asset_name: todo-reminder.zip
        asset_content_type: application/zip
