name: Build and Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Setup JRE
      run: |
        ./create-jre.bat
        
    - name: Create README
      run: |
        ./create_readme.bat
        
    - name: Package Application
      run: |
        ./package.bat
        
    - name: List Files
      shell: pwsh
      run: |
        Get-ChildItem -Path . -Recurse
        Write-Host "Looking for zip file:"
        Get-ChildItem -Path . -Filter *.zip -Recurse
        
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: todo-reminder.zip
        asset_name: todo-reminder.zip
        asset_content_type: application/zip 
